### ISSUE TITLE
`Typed Function References proposal` feature doesn't get enabled

### ISSUE THREAD

**Issue by epsylonix** [WasmEdge/wasmedge-rust-sdk#124]
I'm trying to run a Kotlin-generated Wasm file from Rust embedded WasmEdge. For Kotlin it is required to enable Wasm GC and Function References proposals and though these features are enabled explicitly, module init still fails with this error:

```
[2024-12-02 14:29:06.414] [error] loading failed: malformed value type, Code: 0x111
[2024-12-02 14:29:06.415] [error]     This instruction or syntax requires enabling Typed Function References proposal
[2024-12-02 14:29:06.415] [error]     Bytecode offset: 0x00000011
[2024-12-02 14:29:06.415] [error]     At AST node: recursive type
[2024-12-02 14:29:06.415] [error]     At AST node: recursive type
[2024-12-02 14:29:06.415] [error]     At AST node: type section
[2024-12-02 14:29:06.415] [error]     At AST node: module
[2024-12-02 14:29:06.415] [error]     File name: "kotlin.wasm"
thread 'main' panicked at src/main.rs:24:129:
called `Result::unwrap()` on an `Err` value: Core(Load(MalformedValType))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
   4: jobexecutor::main
             at ./src/main.rs:24:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
```

I'm using the latest versions of `wasmedge` (0.14) and of the `wasmedge-rust-sdk` crate. 

Here is the code:
```rust
use std::error::Error;
use std::collections::HashMap;

use wasmedge_sdk::{config::{CommonConfigOptions, ConfigBuilder}, params, vm::SyncInst, wasi::WasiModule, Module, Store, Vm};

fn main() -> Result<(), Box<dyn Error>> {
    let mut wasi_module = WasiModule::create(None, None, None).unwrap();
    let mut instances: HashMap<String, &mut dyn SyncInst> = HashMap::new();
    instances.insert(wasi_module.name().to_string(), wasi_module.as_mut());

    let config = ConfigBuilder::new(
        CommonConfigOptions::new()
            .function_references(true)
            .gc(true)
    )
        .build()
        .unwrap();

    let mut vm = Vm::new(Store::new(Some(&config), instances).unwrap());

    let module = Module::from_file(None, "kotlin.wasm").unwrap();
    vm.register_module(Some("test"), module).unwrap();
    vm.run_func(Some("test"), "main", params!())?;


    Ok(())
}
```

Running in the standalone mode like this works fine: `wasmedge --enable-function-reference --enable-gc kotlin.wasm`

**Comment by hydai** [comment]
@apepkuss @L-jasmine 
Please check this issue. It seems like the rust sdk doesn't pass the configuration to the C SDK, since the wasmedge CLI can run the same configuration.

**Comment by epsylonix** [comment]
Also it looks like `ExceptionHandling` option is not exposed in Rust API at all. Is it on by default?

**Comment by epsylonix** [comment]
Found an issue in my code, not only VM but also `Module::from_file` requires config: `Module::from_file(None, "kotlin.wasm").unwrap()` should be `Module::from_file(Some(&config), "kotlin.wasm").unwrap()`. Closing this but will create another issue for exposing an option to enable `ExceptionHandling` proposal.
